server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    session:
      timeout: 1800 # Set the session timeout to 3600 seconds (60 minutes)

spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/PersonalFinance
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  data:
    jpa:
      repositories:
        base-package: com.example.myproject.Class

#Google login;
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
                576174807319-cc2dckjms0m47rv9pkfsq2teo2m5dj2b.apps.googleusercontent.com

            client-secret:
                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
logging:
  level:
    org:
      springframework:
        security:
          TRACE
